### ISSUE TITLE
Publish boxer

### ISSUE THREAD

**Issue by non** [retronym/boxer#2]
I wonder if Boxer is in good enough shape to actually publish? I know plenty of folks who'd love to have these kinds of warnings.

If the code is believed to be pretty good, but you aren't interested in releasing/maintaining this plugin, I'd be happy to fork this project and start publishing it myself.

**Comment by retronym** [comment]
I tend to think you'd drown in the noise of warnings here. Once we get configurable warning filtering into the 2.11 compiler series, it might be worthwhile.

This project primarily exists as a way to show how you can incorporate compiler plugin sources into a SBT project; detecting value class boxing was actually just chosen as a cute example of something you might want to analyze.

If you do want to release this analysis, might I suggest adding this to https://github.com/scala/scala-abide? The tool might need to be extended to support rule execution at phases other than typer.

**Comment by SethTisue** [comment]
Abide suggestion, seconded. (or your linter of choice; Abide is our own sentimental favorite)
