### ISSUE TITLE
simpler way?

### ISSUE THREAD

**Issue by fommil** [retronym/boxer#4]
I'm using `packageBin`

https://github.com/fommil/imaginary-friend/blob/6e8c2f6eda840baf01191c080f113e4bb5bd152e/project/ImaginaryFriendBuild.scala#L42-L44

and I'm able to use the compiler plugin in its own test package.

You might be interested in this experiment more generally.

**Comment by retronym** [comment]
Glad you found this a useful starting point. ``package`` vs `packageBin` seems like a six-of-one, half-a-dozen of the other choice. Note that the last modified time that you've omitted means that you will need to manually run `test:clean` after editing the compiler plugin.

**Comment by fommil** [comment]
Nope, the packageBin autoupdates :-)
